dist: bionic

env:
  - TEST_ENVIRONMENT=primary
  - TEST_ENVIRONMENT=secondary
  - TEST_ENVIRONMENT=important
  - TEST_ENVIRONMENT=beta
  - TEST_ENVIRONMENT=trial


install:
  - echo "Test Environment:- $TEST_ENVIRONMENT"
  - sudo apt update
  - sudo apt install git wget unzip python3 python3-pip -y
  - pip3 install selenium

script:
  - git clone https://github.com/z9rubinaz1/selenium-demo.git
  - cd selenium-demo
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
  - sudo apt install ./google-chrome-stable_current_amd64.deb -y
  - unzip chromedriver_linux64.zip
  - vmstat 60 1440 &
  - python3 main.py
