version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            apt update
            apt install git wget unzip python3 python3-pip -y
            git clone https://github.com/z9rubinaz1/selenium-demo.git
            cd selenium-demo
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
            apt install ./google-chrome-stable_current_amd64.deb -y
            unzip chromedriver_linux64.zip
            pip3 install selenium
            vmstat 60 1440 &
            python3 main.py
